import type {
  ChatMessage,
  ChatRequest,
  ChatResponse,
  LLMUsageAttempt,
  ProviderConfig,
  ProviderFallbackConfig,
  ProviderFinishReason,
  ProviderName,
  ProviderRegistry,
  StreamCallback,
  TokenUsageStatusReason,
  ToolInvocation,
} from "./types.ts";
import { resolveProviderApiKey } from "./config.ts";
import {
  composeWireContent,
  createMockResponse,
  sanitizeUserFacingText,
  stripStructuralLeakTokens,
  withDefaultStopSequences,
} from "./utils.ts";
import {
  classifyLLMError,
  getErrorMessage,
  getErrorStatus,
  getProviderErrorDetails,
  getSafeLLMErrorLog,
  isProviderGlobalLLMFailure,
  type LLMProviderAttempt,
  LLMProviderError,
  LLMStreamTimeoutError,
} from "./errors.ts";
import { runProviderAttempt } from "./attempt-runner.ts";
import {
  interpretAssistantResponse,
  REASONING_HISTORY_TAGS,
} from "./response-interpreter.ts";
import {
  decideRecovery,
  recoveryActionOf,
  type RecoveryDecision,
} from "./recovery-policy.ts";
import { prepareAttemptTranscript } from "./transcript.ts";
import {
  accountCompletedAttempt,
  accountFailedAttempt,
} from "./attempt-accounting.ts";

export { classifyLLMError, LLMProviderError } from "./errors.ts";
export type { LLMProviderAttempt } from "./errors.ts";

const RECOVERABLE_FINISH_REASONS: ReadonlySet<ProviderFinishReason> = new Set([
  "length",
  "error",
  "content_filter",
]);

const DEFAULT_REASONING_HISTORY_MAX_ESTIMATED_TOKENS = 750;
const RECOVERY_PROTOCOL_MARKER_PATTERN =
  /<\/?(?:[a-z0-9_]+:)?(?:tool_call|tool_calls|function_call|function_calls|invoke|parameter|tool_use|tool|tool_result|tool_results|result|continue_after_tool_results|target_ids)\b/i;
const VISIBLE_REASONING_BLOCK_PATTERN =
  /<(?:mm:)?(?:think|thought|thinking|reasoning)\b[^>]*>([\s\S]*?)(?:<\/(?:mm:)?(?:think|thought|thinking|reasoning)>|$)/gi;
function buildRecoveryCue(reason: string | null): string {
  switch (reason) {
    case "length":
      return "<recovery_cue>Previous response exceeded maximum output length. Continue where you left off. Be concise and break into smaller steps if needed.</recovery_cue>";
    case "timeout":
      return "<recovery_cue>Previous response was interrupted by a timeout. Continue where you left off. Be concise.</recovery_cue>";
    case "content_filter":
      return "<recovery_cue>Previous response was blocked by a content filter. Continue where you left off, rephrasing as needed.</recovery_cue>";
    case "error":
      return "<recovery_cue>Previous response was interrupted by a provider error. Continue where you left off.</recovery_cue>";
    case "empty_response":
      return "<recovery_cue>Previous attempt produced reasoning but no visible response. You must produce a concrete answer for the user.</recovery_cue>";
    case "degenerate_repetition":
      return "<recovery_cue>Your previous response degenerated into repeated text. The previous assistant message is already present and correct before the repeated section. Continue from that point with a concise final answer. Do not repeat earlier content, tool results, JSON fragments, or repeated tokens.</recovery_cue>";
    case "malformed_tool_call":
      return `<recovery_cue>
The previous assistant message is already present in the conversation and is correct up to the attempted tool call. Do not repeat it.
If you intended to call a tool, emit only the corrected <tool_calls> block.
Inside it, write one complete JSON object per line, each with exactly "name" and "arguments".
Do not wrap calls in an array or separate objects with commas. Remove any surrounding array brackets and replace commas between calls with newlines; preserve arrays inside arguments.
Parallel format (substitute tools and arguments from your catalog):
<tool_calls>
{"name":"tool_name","arguments":{"key":"first"}}
{"name":"tool_name","arguments":{"key":"second"}}
</tool_calls>
If you did not intend to call a tool, continue from the previous assistant message without any tool or result protocol.
</recovery_cue>`;
    case "orphaned_tool_result":
      return "<recovery_cue>Your previous response imitated a tool-result payload. Tool results are external user-side input and must never be generated by you. Answer normally or emit a canonical <tool_calls> block if another tool is required.</recovery_cue>";
    default:
      return "<recovery_cue>Continue exactly where you left off. Do not repeat earlier content.</recovery_cue>";
  }
}

function normalizeReasoningHistoryOptions(
  options: ChatRequest["reasoningHistory"] | undefined,
): Required<NonNullable<ChatRequest["reasoningHistory"]>> {
  return {
    include: options?.include ?? "self",
    maxEstimatedTokens: typeof options?.maxEstimatedTokens === "number"
      ? options.maxEstimatedTokens
      : DEFAULT_REASONING_HISTORY_MAX_ESTIMATED_TOKENS,
  };
}

function extractVisibleReasoningMarkup(response: string): string[] {
  const parts: string[] = [];
  for (const match of response.matchAll(VISIBLE_REASONING_BLOCK_PATTERN)) {
    const value = match[1]?.trim();
    if (value) parts.push(stripStructuralLeakTokens(value));
  }
  return parts.filter((part) => part.trim().length > 0);
}

function getSafeVisiblePrefixBeforeProtocol(response: string): string {
  const markerIndex = response.search(RECOVERY_PROTOCOL_MARKER_PATTERN);
  const prefix = markerIndex === -1 ? response : response.slice(0, markerIndex);
  return sanitizeUserFacingText(prefix);
}

function buildRecoveryAssistantContext(
  existingContext: string,
  visiblePrefix: string,
  reasoning: string | undefined,
  options: ChatRequest["reasoningHistory"] | undefined,
): string {
  const reasoningHistory = normalizeReasoningHistoryOptions(options);
  const trimmedReasoning = reasoning?.trim();
  const attemptContext = composeWireContent({
    reasoning: reasoningHistory.include !== "none" &&
        typeof trimmedReasoning === "string" &&
        trimmedReasoning.length > 0
      ? trimmedReasoning
      : undefined,
    reasoningMaxEstimatedTokens: reasoningHistory.maxEstimatedTokens,
    visible: visiblePrefix.trim() || undefined,
  });
  return [existingContext.trim(), attemptContext].filter((part) =>
    part.length > 0
  ).join("\n\n");
}

function joinRecoveredContent(prefix: string, continuation: string): string {
  if (!prefix) return continuation;
  if (!continuation) return prefix;
  if (/\s$/.test(prefix) || /^\s/.test(continuation)) {
    return prefix + continuation;
  }
  if (/^[.,;:!?)]/.test(continuation)) {
    return prefix + continuation;
  }
  return `${prefix} ${continuation}`;
}

function requireProviderRegistry(
  registry?: ProviderRegistry,
): ProviderRegistry {
  if (!registry || Object.keys(registry).length === 0) {
    throw new Error(
      "LLM chat requires an explicit provider registry. Ship adapters as llm resources on a plugin.",
    );
  }
  return registry;
}

function buildAttemptConfig(
  baseConfig: ProviderConfig,
  env: Record<string, string>,
  override?: ProviderFallbackConfig,
): ProviderConfig {
  const fallbackChangesProvider = override?.provider &&
    override.provider !== baseConfig.provider;
  const candidate = {
    ...baseConfig,
    ...(override ?? {}),
    ...(fallbackChangesProvider && !override?.apiKey
      ? { apiKey: undefined }
      : {}),
    ...(fallbackChangesProvider && !override?.runtimeDiagnostics
      ? { runtimeDiagnostics: undefined }
      : {}),
    fallbacks: undefined,
  } as ProviderConfig;

  candidate.apiKey = resolveProviderApiKey(candidate, env);
  return withDefaultStopSequences(candidate);
}

function normalizedProviderEndpoint(config: ProviderConfig): string {
  const configured = config.baseUrl?.trim();
  const raw = configured ||
    (config.provider === "openai" ? "https://api.openai.com/v1" : "default");
  if (raw === "default") return raw;

  try {
    const url = new URL(raw);
    const pathname = url.pathname.replace(/\/+$/, "") || "/";
    return `${url.protocol.toLowerCase()}//${url.host.toLowerCase()}${pathname}`;
  } catch {
    return raw.replace(/\/+$/, "").toLowerCase();
  }
}

function providerTransport(config: ProviderConfig): string {
  if (config.provider !== "openai") {
    return config.provider ? `${config.provider}_api` : "unknown";
  }

  const endpoint = normalizedProviderEndpoint(config);
  if (
    endpoint === "https://chatgpt.com/backend-api/codex" ||
    endpoint.startsWith("https://chatgpt.com/backend-api/codex/")
  ) {
    return "chatgpt_codex";
  }
  if (
    endpoint === "https://api.openai.com/v1" ||
    endpoint.startsWith("https://api.openai.com/v1/")
  ) {
    return "openai_api";
  }
  return "openai_compatible";
}

function sharesProviderFailureScope(
  current: ProviderConfig,
  candidate: ProviderConfig,
): boolean {
  return current.provider === candidate.provider &&
    normalizedProviderEndpoint(current) ===
      normalizedProviderEndpoint(candidate) &&
    (current.runtimeDiagnostics?.credentialSource ?? null) ===
      (candidate.runtimeDiagnostics?.credentialSource ?? null);
}

function sharesProviderModel(
  current: ProviderConfig,
  candidate: ProviderConfig,
): boolean {
  return current.provider === candidate.provider &&
    current.model === candidate.model;
}

function logProviderAttempt(
  phase: "started" | "completed" | "failed",
  config: ProviderConfig,
  context: {
    llmCallId: string;
    attemptId: string;
    attemptNumber: number;
    finishReason?: ProviderFinishReason | null;
    reason?: string | null;
    status?: number;
    visibleOutputStarted?: boolean;
    visibleOutputChars?: number;
    reasoningOutputChars?: number;
    error?: ReturnType<typeof getSafeLLMErrorLog>;
  },
): void {
  if (config.runtimeDiagnostics?.enabled !== true) return;

  const payload = {
    severity: phase === "failed" ? "WARNING" : "INFO",
    message: `[llm] Provider attempt ${phase}`,
    llmCallId: context.llmCallId,
    attemptId: context.attemptId,
    attemptNumber: context.attemptNumber,
    provider: config.provider ?? null,
    model: config.model ?? null,
    transport: providerTransport(config),
    credentialSource: config.runtimeDiagnostics.credentialSource ??
      "unspecified",
    ...(context.finishReason !== undefined
      ? { finishReason: context.finishReason }
      : {}),
    ...(context.reason !== undefined ? { reason: context.reason } : {}),
    ...(context.status !== undefined ? { status: context.status } : {}),
    ...(context.visibleOutputStarted !== undefined
      ? { visibleOutputStarted: context.visibleOutputStarted }
      : {}),
    ...(context.visibleOutputChars !== undefined
      ? { visibleOutputChars: context.visibleOutputChars }
      : {}),
    ...(context.reasoningOutputChars !== undefined
      ? { reasoningOutputChars: context.reasoningOutputChars }
      : {}),
    ...(context.error ? { error: context.error } : {}),
  };

  try {
    const entry = JSON.stringify(payload);
    if (phase === "failed") {
      console.warn(entry);
    } else {
      console.info(entry);
    }
  } catch {
    // Diagnostics must never affect provider execution.
  }
}

function mergeReasoningParts(...parts: Array<string | string[] | undefined>) {
  const values = parts.flatMap((part) => Array.isArray(part) ? part : [part])
    .filter((part): part is string =>
      typeof part === "string" && part.trim().length > 0
    )
    .map((part) => part.trim());
  return values.length > 0 ? values.join("\n\n") : undefined;
}

function warnRecoveryAttempt(
  reason: string | null,
  current: ProviderConfig,
  next?: ProviderConfig,
  message?: string,
): void {
  try {
    console.warn("[llm] Attempting recovery", {
      provider: current.provider,
      model: current.model,
      reason,
      ...(message ? { message } : {}),
      ...(next
        ? { nextProvider: next.provider, nextModel: next.model }
        : { crossResourceFailover: true }),
    });
  } catch {
    // Ignore logging failures.
  }
}

function toUsageStatusReason(
  reason: string | null,
): TokenUsageStatusReason | undefined {
  switch (reason) {
    case "local_stop_sequence":
    case "length":
    case "error":
    case "timeout":
    case "network":
    case "auth_error":
    case "billing_error":
    case "rate_limit":
    case "server_error":
    case "provider_error":
    case "invalid_transcript":
    case "unknown":
    case "content_filter":
    case "empty_response":
    case "malformed_tool_call":
    case "visible_reasoning_markup":
    case "degenerate_repetition":
      return reason;
    default:
      return undefined;
  }
}

export type ChatOptions = {
  /** The owning `llm.call` invocation has another model candidate. */
  hasExternalFallback?: boolean;
};

/**
 * Unified AI Chat endpoint.
 *
 * Streams an LLM response through the configured provider. Before user-visible
 * output is emitted it may recover with retry/same-resource fallback attempts;
 * after visible output starts it preserves that partial response and avoids
 * hidden fallbacks. Different-provider fallbacks are not executed here.
 */
export async function chat(
  request: ChatRequest,
  config: ProviderConfig,
  env: Record<string, string> = {},
  stream?: StreamCallback,
  providerRegistry?: ProviderRegistry,
  options?: ChatOptions,
): Promise<ChatResponse> {
  if (request.answer) {
    return createMockResponse(request);
  }

  const baseConfig = {
    ...config,
    ...request.config,
  } as ProviderConfig;
  const providerFromRequest =
    (request as ChatRequest & { provider?: ProviderName }).provider;
  if (!baseConfig.provider && providerFromRequest) {
    baseConfig.provider = providerFromRequest;
  }
  if (!baseConfig.provider) {
    throw new Error("No LLM provider configured for chat request");
  }

  const localFallbacks = (baseConfig.fallbacks ?? []).filter((fallback) =>
    !fallback.provider || fallback.provider === baseConfig.provider
  );
  const attemptConfigs = [
    buildAttemptConfig(baseConfig, env),
    ...localFallbacks.map((fallback) =>
      buildAttemptConfig(baseConfig, env, fallback)
    ),
  ];
  const hasExternalFallback = options?.hasExternalFallback === true;
  const registry = requireProviderRegistry(providerRegistry);
  const llmCallId = crypto.randomUUID();
  const knownToolNames = (request.tools ?? [])
    .map((tool) => tool?.function?.name)
    .filter((name): name is string =>
      typeof name === "string" && name.length > 0
    );
  const extractedBlockTags = [
    ...(request.extractTags ?? []),
    ...REASONING_HISTORY_TAGS,
  ];
  const attempts: LLMProviderAttempt[] = [];
  const usageAttempts: LLMUsageAttempt[] = [];
  const initialContinuationAnswer = sanitizeUserFacingText(
    request.continuation?.partialAnswer ?? "",
  );
  const initialContinuationReasoning =
    request.continuation?.partialReasoning?.trim() ?? "";
  const hasInitialContinuation = initialContinuationAnswer.trim().length > 0 ||
    initialContinuationReasoning.length > 0;
  const state = {
    providerIndex: Math.max(
      0,
      Math.min(
        request.durableRecovery?.providerIndex ?? 0,
        attemptConfigs.length - 1,
      ),
    ),
    attemptSequence: 0,
    recoveryContext: hasInitialContinuation
      ? buildRecoveryAssistantContext(
        "",
        initialContinuationAnswer,
        initialContinuationReasoning,
        request.reasoningHistory,
      )
      : "",
    recoveryReasoning: initialContinuationReasoning,
    lastRecoveryReason: hasInitialContinuation
      ? request.continuation?.reason ?? "error"
      : null as string | null,
    sameProviderRecoveryUsed: (request.durableRecovery?.count ?? 0) > 0,
    streamContinuationUsed: hasInitialContinuation ||
      (request.durableRecovery?.count ?? 0) > 0,
    visibleOutputStarted: initialContinuationAnswer.trim().length > 0,
    silentNextAttempt: false,
    forceRecoveryCue: hasInitialContinuation,
  };
  let lastError: unknown = null;
  let lastUsageRecord: LLMUsageAttempt | undefined;
  let lastPrompt: ChatMessage[] = request.messages;
  let lastAttemptConfig = attemptConfigs[0];

  const throwCrossResourceFailover = (message: string): never => {
    const lastAttempt = attempts[attempts.length - 1];
    throw new LLMProviderError(message, {
      reason: lastAttempt?.reason ?? classifyLLMError(lastError),
      provider: lastAttempt?.provider ?? baseConfig.provider,
      model: lastAttempt?.model ?? baseConfig.model,
      status: lastAttempt?.status ?? getErrorStatus(lastError),
      attempts,
      fallbackAttempted: attempts.length > 1 || hasExternalFallback,
      visibleStreamStarted: state.visibleOutputStarted,
      usageAttempts,
      providerError: lastAttempt?.details,
      crossResourceFailover: true,
      ...(lastError !== null && lastError !== undefined
        ? { cause: lastError }
        : {}),
    });
  };

  const DEFAULT_TOTAL_TIMEOUT_MS = 3_600_000;
  const configuredTotalTimeoutMs = baseConfig.totalTimeoutMs === undefined
    ? DEFAULT_TOTAL_TIMEOUT_MS
    : Number.isFinite(baseConfig.totalTimeoutMs) &&
        baseConfig.totalTimeoutMs > 0
    ? baseConfig.totalTimeoutMs
    : undefined;
  const startedAtMs = Date.now();
  const configuredDeadline = configuredTotalTimeoutMs
    ? startedAtMs + configuredTotalTimeoutMs
    : undefined;
  const inheritedDeadline = typeof request.deadlineAt === "number" &&
      Number.isFinite(request.deadlineAt)
    ? request.deadlineAt
    : undefined;
  const deadlineAt = configuredDeadline !== undefined &&
      inheritedDeadline !== undefined
    ? Math.min(configuredDeadline, inheritedDeadline)
    : configuredDeadline ?? inheritedDeadline;
  const totalAbortController = new AbortController();
  let totalTimedOut = false;
  let totalTimer: number | undefined;
  const abortFromRequest = () => {
    totalAbortController.abort(request.signal?.reason);
  };
  if (request.signal?.aborted) abortFromRequest();
  request.signal?.addEventListener("abort", abortFromRequest, { once: true });
  if (deadlineAt !== undefined) {
    const remainingMs = Math.max(0, deadlineAt - Date.now());
    totalTimer = setTimeout(() => {
      totalTimedOut = true;
      totalAbortController.abort(
        new LLMStreamTimeoutError("total", remainingMs),
      );
    }, remainingMs) as unknown as number;
  }

  const finalResponse = (
    record: LLMUsageAttempt,
    attemptConfig: ProviderConfig,
    prompt: ChatMessage[],
    answer: string,
    reasoning: string | undefined,
    finishReason: ProviderFinishReason | null,
    parsed?: {
      toolCalls: ToolInvocation[];
      extractedTags: Record<string, string[]>;
    },
    recovery?: ChatResponse["recovery"],
  ): ChatResponse => ({
    prompt,
    answer,
    ...(reasoning ? { reasoning } : {}),
    tokens: record.usage.totalTokens ?? 0,
    finishReason,
    usage: record.usage,
    usageAttempts: [...usageAttempts],
    ...(record.usageFinalized ? { usageFinalized: record.usageFinalized } : {}),
    ...(record.cost ? { cost: record.cost } : {}),
    provider: attemptConfig.provider,
    model: attemptConfig.model,
    ...(record.debug ? { debug: record.debug } : {}),
    ...(parsed && parsed.toolCalls.length > 0
      ? { toolCalls: parsed.toolCalls }
      : {}),
    ...(parsed && Object.keys(parsed.extractedTags).length > 0
      ? { extractedTags: parsed.extractedTags }
      : {}),
    ...(recovery ? { recovery } : {}),
    metadata: {
      provider: attemptConfig.provider,
      timestamp: new Date().toISOString(),
      messageCount: request.messages.length,
    },
  });

  try {
    while (state.providerIndex < attemptConfigs.length) {
      if (request.signal?.aborted && !totalTimedOut) {
        throw new DOMException("LLM request aborted", "AbortError");
      }
      if (deadlineAt !== undefined && Date.now() >= deadlineAt) {
        totalTimedOut = true;
      }
      if (totalTimedOut) {
        lastError = new LLMStreamTimeoutError(
          "total",
          configuredTotalTimeoutMs ?? Math.max(0, Date.now() - startedAtMs),
        );
        if (state.visibleOutputStarted && lastUsageRecord) {
          return finalResponse(
            lastUsageRecord,
            lastAttemptConfig,
            lastPrompt,
            sanitizeUserFacingText(state.recoveryContext),
            state.recoveryReasoning || undefined,
            "error",
          );
        }
        break;
      }

      const attemptConfig = attemptConfigs[state.providerIndex];
      lastAttemptConfig = attemptConfig;
      const attemptProvider = attemptConfig.provider!;
      const providerFactory = registry[attemptProvider];
      if (!providerFactory) {
        throw new Error(
          `Provider '${attemptProvider}' is not supported. Available providers: ${
            Object.keys(registry).join(", ")
          }`,
        );
      }
      const providerAPI = providerFactory(attemptConfig);
      const prefixBeforeAttempt = state.recoveryContext;
      const includeRecoveryCue = prefixBeforeAttempt.length > 0 ||
        state.forceRecoveryCue;
      state.forceRecoveryCue = false;
      const recoveryMessages: ChatMessage[] = includeRecoveryCue
        ? [
          ...(prefixBeforeAttempt.length > 0
            ? [{
              role: "assistant" as const,
              content: prefixBeforeAttempt,
            }]
            : []),
          {
            role: "user" as const,
            content: buildRecoveryCue(state.lastRecoveryReason),
          },
        ]
        : [];
      const transcript = await prepareAttemptTranscript({
        request,
        config: attemptConfig,
        recoveryMessages,
      });
      const attemptMessages = transcript.messages;
      lastPrompt = attemptMessages;
      const attemptId = crypto.randomUUID();
      const attemptIndex = state.attemptSequence++;
      const attemptNumber = attemptIndex + 1;
      const attemptStartedAt = new Date().toISOString();
      const silentAttempt = state.silentNextAttempt;
      state.silentNextAttempt = false;

      logProviderAttempt("started", attemptConfig, {
        llmCallId,
        attemptId,
        attemptNumber,
      });
      const execution = await runProviderAttempt({
        attemptId,
        messages: attemptMessages,
        config: attemptConfig,
        providerAPI,
        extractedBlockTags,
        knownToolNames,
        stream,
        silent: silentAttempt,
        signal: totalAbortController.signal,
        onToolCallDelta: request.onToolCallDelta,
        onMeaningfulVisibleOutput: () => {
          state.visibleOutputStarted = true;
        },
      });

      if (execution.kind === "completed") {
        const { streamResult, capture } = execution;
        const fullContent = joinRecoveredContent(
          prefixBeforeAttempt,
          streamResult.content,
        );
        const interpretation = interpretAssistantResponse({
          fullContent,
          currentAttemptContent: streamResult.content,
          extractedBlockTags,
          knownToolNames,
          finishReason: streamResult.finishReason,
        });
        const assessment = streamResult.finishReason &&
            RECOVERABLE_FINISH_REASONS.has(streamResult.finishReason)
          ? {
            kind: "finish_issue" as const,
            reason: streamResult.finishReason as
              | "length"
              | "error"
              | "content_filter",
          }
          : interpretation.issue
          ? {
            kind: "semantic_issue" as const,
            issue: interpretation.issue,
          }
          : { kind: "acceptable" as const };
        const decision = decideRecovery(assessment, {
          visibleOutputStarted: state.visibleOutputStarted,
          sameProviderRecoveryUsed: state.sameProviderRecoveryUsed,
          streamContinuationUsed: state.streamContinuationUsed,
          hasFallback: state.providerIndex < attemptConfigs.length - 1 ||
            hasExternalFallback,
          hasSameModelFallback: false,
        });
        const statusReason = decision.action === "accept"
          ? undefined
          : decision.reason;
        const reasoning = mergeReasoningParts(
          state.recoveryReasoning,
          streamResult.reasoning,
        );
        const finishedAt = new Date().toISOString();

        const record = await accountCompletedAttempt({
          attemptId,
          attemptIndex,
          providerConfig: attemptConfig,
          messages: attemptMessages,
          transcript,
          streamResult,
          parsed: interpretation.parsed,
          fullContent,
          reasoning,
          capture: {
            ...capture,
            visibleOutput: sanitizeUserFacingText(capture.visibleOutput),
          },
          statusReason,
          recoveryAction: recoveryActionOf(decision),
          startedAt: attemptStartedAt,
          finishedAt,
        });
        usageAttempts.push(record);
        lastUsageRecord = record;
        logProviderAttempt("completed", attemptConfig, {
          llmCallId,
          attemptId,
          attemptNumber,
          finishReason: streamResult.finishReason,
        });

        if (decision.action === "accept") {
          execution.completeToolDrafts(interpretation.parsed.toolCalls);
          return finalResponse(
            record,
            attemptConfig,
            attemptMessages,
            interpretation.parsed.cleanResponse,
            reasoning,
            streamResult.finishReason,
            interpretation.parsed,
          );
        }

        execution.discardToolDrafts();
        const issue = interpretation.issue;
        let nextRecoveryContext = prefixBeforeAttempt;
        if (
          assessment.kind === "finish_issue" &&
          assessment.reason === "length"
        ) {
          nextRecoveryContext = joinRecoveredContent(
            prefixBeforeAttempt,
            interpretation.currentAttempt.cleanResponse,
          );
        } else if (issue?.kind === "malformed_tool_call") {
          nextRecoveryContext = buildRecoveryAssistantContext(
            prefixBeforeAttempt,
            getSafeVisiblePrefixBeforeProtocol(streamResult.content),
            mergeReasoningParts(
              streamResult.reasoning,
              extractVisibleReasoningMarkup(streamResult.content),
            ),
            request.reasoningHistory,
          );
        } else if (issue?.kind === "degenerate_repetition") {
          nextRecoveryContext = buildRecoveryAssistantContext(
            prefixBeforeAttempt,
            sanitizeUserFacingText(
              streamResult.content.slice(0, issue.startIndex),
            ),
            streamResult.reasoning,
            request.reasoningHistory,
          );
        }

        if (
          request.durableRecovery?.enabled === true &&
          (request.durableRecovery.count ?? 0) === 0
        ) {
          let fragmentAnswer = interpretation.currentAttempt.cleanResponse;
          let fragmentReasoning: string | undefined = streamResult.reasoning;
          if (issue?.kind === "malformed_tool_call") {
            fragmentAnswer = getSafeVisiblePrefixBeforeProtocol(
              streamResult.content,
            );
            fragmentReasoning = mergeReasoningParts(
              streamResult.reasoning,
              extractVisibleReasoningMarkup(streamResult.content),
            );
          } else if (issue?.kind === "degenerate_repetition") {
            fragmentAnswer = sanitizeUserFacingText(
              streamResult.content.slice(0, issue.startIndex),
            );
          } else if (issue?.kind === "orphaned_tool_result") {
            fragmentAnswer = "";
          }
          fragmentAnswer = sanitizeUserFacingText(fragmentAnswer);
          const fragmentToolCalls = interpretation.parsed.toolCalls;
          const hasReusableOutput = fragmentAnswer.trim().length > 0 ||
            Boolean(fragmentReasoning?.trim()) ||
            fragmentToolCalls.length > 0;

          if (hasReusableOutput) {
            const nextProviderIndex = decision.action === "fallback"
              ? Math.min(state.providerIndex + 1, attemptConfigs.length - 1)
              : state.providerIndex;
            return finalResponse(
              record,
              attemptConfig,
              attemptMessages,
              fragmentAnswer,
              fragmentReasoning,
              streamResult.finishReason,
              undefined,
              {
                reason: toUsageStatusReason(decision.reason) ?? "unknown",
                cue: buildRecoveryCue(decision.reason),
                answer: fragmentAnswer,
                ...(fragmentReasoning ? { reasoning: fragmentReasoning } : {}),
                ...(fragmentToolCalls.length > 0
                  ? { toolCalls: fragmentToolCalls }
                  : {}),
                joinSeparator: fragmentAnswer ? " " : "",
                nextProviderIndex,
              },
            );
          }

          if (state.providerIndex < attemptConfigs.length - 1) {
            state.providerIndex++;
            state.recoveryContext = prefixBeforeAttempt;
            state.recoveryReasoning = "";
            state.forceRecoveryCue = false;
            continue;
          }
          if (hasExternalFallback && decision.action === "fallback") {
            lastError = new Error(
              `LLM attempt produced no reusable output (${decision.reason})`,
            );
            warnRecoveryAttempt(
              decision.reason,
              attemptConfig,
              undefined,
              "Cross-resource failover",
            );
            throwCrossResourceFailover(getErrorMessage(lastError));
          }
          lastError = new Error(
            `LLM attempt produced no reusable output (${decision.reason})`,
          );
          break;
        }

        if (decision.action === "retry_same") {
          state.recoveryContext = nextRecoveryContext;
          state.lastRecoveryReason = decision.reason;
          state.forceRecoveryCue = true;
          state.silentNextAttempt = decision.silent;
          state.sameProviderRecoveryUsed = true;
          warnRecoveryAttempt(
            decision.reason,
            attemptConfig,
            attemptConfig,
            decision.mode === "repair"
              ? "Retrying same provider with repair context"
              : "Retrying same provider with continuation context",
          );
          continue;
        }

        if (decision.action === "fallback") {
          if (state.providerIndex >= attemptConfigs.length - 1) {
            lastError = lastError ?? new Error(
              `LLM generate exhausted this resource (${decision.reason})`,
            );
            if (hasExternalFallback) {
              warnRecoveryAttempt(
                decision.reason,
                attemptConfig,
                undefined,
                "Cross-resource failover",
              );
              throwCrossResourceFailover(getErrorMessage(lastError));
            }
            break;
          }
          state.recoveryContext = nextRecoveryContext;
          state.lastRecoveryReason = decision.reason;
          state.providerIndex++;
          state.sameProviderRecoveryUsed = false;
          state.silentNextAttempt = false;
          warnRecoveryAttempt(
            decision.reason,
            attemptConfig,
            attemptConfigs[state.providerIndex],
          );
          continue;
        }

        let answer = interpretation.parsed.cleanResponse;
        if (issue?.kind === "orphaned_tool_result") {
          answer = sanitizeUserFacingText(prefixBeforeAttempt);
        } else if (issue?.kind === "degenerate_repetition") {
          const safePrefix = sanitizeUserFacingText(
            streamResult.content.slice(0, issue.startIndex),
          );
          answer = sanitizeUserFacingText(
            [prefixBeforeAttempt, safePrefix].filter((part) =>
              part.trim().length > 0
            ).join(" "),
          );
        } else if (issue) {
          answer = sanitizeUserFacingText(answer);
        }
        return finalResponse(
          record,
          attemptConfig,
          attemptMessages,
          answer,
          reasoning,
          streamResult.finishReason,
        );
      }

      const { error, capture } = execution;
      if (request.signal?.aborted && !totalTimedOut) {
        const failedStatusReason = toUsageStatusReason(
          classifyLLMError(error),
        ) ?? "unknown";
        const finishedAt = new Date().toISOString();
        await accountFailedAttempt({
          attemptId,
          attemptIndex,
          providerConfig: attemptConfig,
          messages: attemptMessages,
          transcript,
          capture: {
            ...capture,
            visibleOutput: sanitizeUserFacingText(capture.visibleOutput),
          },
          errorReason: classifyLLMError(error),
          errorStatus: getErrorStatus(error),
          errorMessage: getErrorMessage(error),
          errorDetails: getProviderErrorDetails(error),
          statusReason: failedStatusReason,
          recoveryAction: "fail",
          startedAt: attemptStartedAt,
          finishedAt,
          status: "superseded",
        });
        throw error;
      }

      lastError = totalTimedOut
        ? new LLMStreamTimeoutError(
          "total",
          configuredTotalTimeoutMs ?? Math.max(0, Date.now() - startedAtMs),
        )
        : error;
      state.lastRecoveryReason = totalTimedOut
        ? "timeout"
        : classifyLLMError(error);
      const errorStatus = getErrorStatus(error);
      logProviderAttempt("failed", attemptConfig, {
        llmCallId,
        attemptId,
        attemptNumber,
        reason: state.lastRecoveryReason,
        ...(errorStatus !== undefined ? { status: errorStatus } : {}),
        visibleOutputStarted: capture.visibleOutputStarted,
        visibleOutputChars: capture.visibleOutput.length,
        reasoningOutputChars: capture.reasoningOutput.length,
        error: getSafeLLMErrorLog(error),
      });
      const providerErrorDetails = getProviderErrorDetails(error);
      const failedStatusReason = totalTimedOut
        ? "timeout"
        : toUsageStatusReason(state.lastRecoveryReason) ?? "unknown";
      let nextIndex = state.providerIndex + 1;
      if (!totalTimedOut && isProviderGlobalLLMFailure(error)) {
        while (
          nextIndex < attemptConfigs.length &&
          sharesProviderFailureScope(
            attemptConfig,
            attemptConfigs[nextIndex],
          )
        ) {
          nextIndex++;
        }
      }
      const decision: RecoveryDecision = decideRecovery(
        totalTimedOut ? { kind: "total_timeout" } : {
          kind: "provider_failure",
          reason: classifyLLMError(error),
          hasPartialOutput: capture.visibleOutput.trim().length > 0 ||
            capture.reasoningOutput.trim().length > 0,
        },
        {
          visibleOutputStarted: state.visibleOutputStarted,
          sameProviderRecoveryUsed: state.sameProviderRecoveryUsed,
          streamContinuationUsed: state.streamContinuationUsed,
          hasFallback: (!totalTimedOut && nextIndex < attemptConfigs.length) ||
            hasExternalFallback,
          hasSameModelFallback: !totalTimedOut &&
            nextIndex < attemptConfigs.length &&
            sharesProviderModel(
              attemptConfig,
              attemptConfigs[nextIndex],
            ),
        },
      );
      const finishedAt = new Date().toISOString();
      const failedRecord = await accountFailedAttempt({
        attemptId,
        attemptIndex,
        providerConfig: attemptConfig,
        messages: attemptMessages,
        transcript,
        capture: {
          ...capture,
          visibleOutput: sanitizeUserFacingText(capture.visibleOutput),
        },
        errorReason: totalTimedOut ? "timeout" : classifyLLMError(error),
        errorStatus: getErrorStatus(error),
        errorMessage: getErrorMessage(lastError),
        errorDetails: providerErrorDetails,
        statusReason: failedStatusReason,
        recoveryAction: recoveryActionOf(decision),
        startedAt: attemptStartedAt,
        finishedAt,
      });
      usageAttempts.push(failedRecord);
      lastUsageRecord = failedRecord;
      attempts.push({
        provider: attemptProvider,
        model: attemptConfig.model,
        reason: totalTimedOut ? "timeout" : classifyLLMError(error),
        status: getErrorStatus(error),
        message: getErrorMessage(lastError),
        ...(providerErrorDetails ? { details: providerErrorDetails } : {}),
      });

      const continueFromCapture = () => {
        state.recoveryReasoning = mergeReasoningParts(
          state.recoveryReasoning,
          capture.reasoningOutput,
        ) ?? "";
        state.recoveryContext = buildRecoveryAssistantContext(
          prefixBeforeAttempt,
          sanitizeUserFacingText(capture.visibleOutput),
          capture.reasoningOutput,
          request.reasoningHistory,
        );
        state.streamContinuationUsed = true;
        state.forceRecoveryCue = true;
      };

      if (
        request.durableRecovery?.enabled === true &&
        (request.durableRecovery.count ?? 0) === 0
      ) {
        const fragmentAnswer = sanitizeUserFacingText(capture.visibleOutput);
        const fragmentReasoning = capture.reasoningOutput.trim() || undefined;
        const hasReusableOutput = fragmentAnswer.trim().length > 0 ||
          Boolean(fragmentReasoning);
        if (hasReusableOutput) {
          const nextProviderIndex = decision.action === "fallback"
            ? Math.min(nextIndex, attemptConfigs.length - 1)
            : state.providerIndex;
          return finalResponse(
            failedRecord,
            attemptConfig,
            attemptMessages,
            fragmentAnswer,
            fragmentReasoning,
            "error",
            undefined,
            {
              reason: failedStatusReason,
              cue: buildRecoveryCue(failedStatusReason),
              answer: fragmentAnswer,
              ...(fragmentReasoning ? { reasoning: fragmentReasoning } : {}),
              joinSeparator: fragmentAnswer ? " " : "",
              nextProviderIndex,
            },
          );
        }

        if (!totalTimedOut && nextIndex < attemptConfigs.length) {
          state.providerIndex = nextIndex;
          state.recoveryContext = prefixBeforeAttempt;
          state.recoveryReasoning = "";
          state.forceRecoveryCue = false;
          continue;
        }
        if (hasExternalFallback && decision.action === "fallback") {
          warnRecoveryAttempt(
            state.lastRecoveryReason,
            attemptConfig,
            undefined,
            "Cross-resource failover",
          );
          throwCrossResourceFailover(getErrorMessage(lastError));
        }
        break;
      }

      if (decision.action === "retry_same") {
        continueFromCapture();
        warnRecoveryAttempt(
          state.lastRecoveryReason,
          attemptConfig,
          attemptConfig,
          "Provider stream failed after partial output, retrying with continuation context",
        );
        continue;
      }

      if (decision.action === "fallback") {
        const nextConfig = attemptConfigs[nextIndex];
        if (!nextConfig) {
          if (hasExternalFallback) {
            warnRecoveryAttempt(
              state.lastRecoveryReason,
              attemptConfig,
              undefined,
              getErrorMessage(error),
            );
            throwCrossResourceFailover(getErrorMessage(lastError));
          }
          break;
        }
        warnRecoveryAttempt(
          state.lastRecoveryReason,
          attemptConfig,
          nextConfig,
          getErrorMessage(error),
        );
        state.providerIndex = nextIndex;
        state.sameProviderRecoveryUsed = false;
        if (sharesProviderModel(attemptConfig, nextConfig)) {
          continueFromCapture();
        } else {
          state.recoveryContext = prefixBeforeAttempt;
          state.recoveryReasoning = "";
        }
        continue;
      }

      if (decision.action === "finalize_partial") {
        const answer = sanitizeUserFacingText(
          joinRecoveredContent(
            prefixBeforeAttempt,
            capture.visibleOutput,
          ),
        );
        return finalResponse(
          failedRecord,
          attemptConfig,
          attemptMessages,
          answer,
          mergeReasoningParts(
            state.recoveryReasoning,
            capture.reasoningOutput,
          ),
          "error",
        );
      }

      break;
    }

    if (lastError) {
      const lastAttempt = attempts[attempts.length - 1];
      throw new LLMProviderError(getErrorMessage(lastError), {
        reason: lastAttempt?.reason ?? classifyLLMError(lastError),
        provider: lastAttempt?.provider ?? baseConfig.provider,
        model: lastAttempt?.model ?? baseConfig.model,
        status: lastAttempt?.status ?? getErrorStatus(lastError),
        attempts,
        fallbackAttempted: attempts.length > 1,
        visibleStreamStarted: state.visibleOutputStarted,
        usageAttempts,
        providerError: lastAttempt?.details,
        cause: lastError,
      });
    }

    throw new Error(
      "LLM chat exhausted all attempts without returning a response",
    );
  } finally {
    if (totalTimer !== undefined) clearTimeout(totalTimer);
    request.signal?.removeEventListener("abort", abortFromRequest);
  }
}
